# Generated by Django 2.2.3 on 2019-08-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
